server.port: 8081

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth/
  resource: gateway
  bearer-only: true # You can't auth from this application

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

zuul:
  routes:
    secured:
      path: /secured/**
      sensitiveHeaders:
      url: http://localhost:8084/secured
    open:
      path: /open/**
      url: http://localhost:8084/

channelManagementEnabled: false

access-control-max-age: 86400
