server.port: 8081

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth/
  resource: gateway
  bearer-only: true # You can't auth from this application

#Actuator
management:
  security:
    enabled: false

endpoints:
  enabled: true
  info:
    enabled: true
  health:
    enabled: true

zuul:
  routes:
    # The test route
    test:
      path: /test/**
      url: http://localhost:8084/

channelManagementEnabled: false

access-control-max-age: 86400
