server.port: 8084

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth/
  resource: resource
  bearer-only: true # You can't auth from this application

#Actuator
management:
  security:
    enabled: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: true
