server.port: 8084

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth/
  resource: resource
  bearer-only: true # You can't auth from this application
  principal-attribute: preferred_username

#Actuator
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
