micronaut:
  server:
    port: 8081
  application:
    name: resource-mn

security:
  token:
    issuer: http://localhost:8080/auth/realms/master

keycloak:
  realm-id: master
  base-url: http://localhost:8080
  eager-load-public-keys: false

